### ISSUE TITLE
any docs

### ISSUE THREAD

**Issue by bartoss77** [jakubsacha/adminlte#11]
Hi,
is there any docs how to use it extend left nav pages actions in base app ?

**Comment by jakubsacha** [comment]
not yet. sorry.

**Comment by JoseCage** [comment]
Hi @jakubsacha. Can you please create  guide for this repo? Your package looks nice, but we need a doc to follow the guidelines...

**Comment by jakubsacha** [comment]
Hey,

Sorry i do not maintain that anymore. Do want to take it over?

**Comment by JoseCage** [comment]
Ahm right. I thought the package was "still in development mode" because I need to implement a management area in a system I'm doing with laravel and I am looking for modules that meet me in this matter and in the middle of it found his. :octocat:  :package:
