### ISSUE TITLE
How about using Datatables?

### ISSUE THREAD

**Issue by irazasyed** [jakubsacha/adminlte#5]
Why not use datatables for all the tables in panel with full support like search, pagination, actions and other features.

There are already some good packages for laravel which makes it easier to integrate datatables.

**Comment by jakubsacha** [comment]
looks like we will not handle that.

**Comment by jakubsacha** [comment]
Hey boys,

It took some time, but i started datatable implementation with laravel 5 support. Fell free to contribute:)

Best

**Comment by irazasyed** [comment]
Hey @jakubsacha 

Sounds good :+1:
